<?php

function getDefaultAttribute(){
$attr=array('sku', 'sku_type',
    'small_image',
    'small_image_label',
    'special_from_date',
    'special_price',
    'special_to_date',
    'status',
    'style',
    'tax_class_id',
    'thumbnail',
    'thumbnail_label',
    'tier_price',
    'updated_at',
    'url_key',
    'url_path',
    'se_config_allow_message',
    'use_config_email_template',
    'use_config_is_redeemable',
     'use_config_lifetime',
   'visibility',
    'weight',
    'weight_type',
    'short_description',
    'recurring_profile',
    'price_view',
     'price_type',
   ' price',
    'weight',
    'page_layout',
    'options_container',
    'name',
    'msrp_display_actual_price_type',
     'meta_title',
   ' meta_keyword',
    'meta_description',
    'media_gallery',
    'options_container',
    'name',
    'msrp_display_actual_price_type',
    'meta_title',
    'custom_layout_update',
    'description',
    'email_template',
    'custom_design_to',
    'custom_design_from',
    'custom_design',
    'visibility',
    'use_config_allow_message',
    'price',
    'open_amount_max',
    'open_amount_min',
    'required_option',
    'created_at',
    'category_ids',
    'meta_keyword',
    'minimal_price'.
    'msrp',
    'msrp',
    'msrp_enabled',
    'gallery',
    'gift_message_available',
    'gift_wrapping_available',
    'group_price',
    'has_options',
    'image',
    'image_label'
    
    );

    return $attr;
    
    
    }
?>