<!-- Google Code for purchase_conversion_cleverppc Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 940384895;
var google_conversion_language = "en";
var google_conversion_format = "2";
var google_conversion_color = "ffffff";
var google_conversion_label = "PJCiCN7nsGUQ_8S0wAM";
var google_conversion_value = 4007045;
var google_conversion_currency = "INR";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/940384895/?value=4007045&amp;currency_code=INR&amp;label=PJCiCN7nsGUQ_8S0wAM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>