<?php
/**
 * Template for Rodrigo_Munoz_ conversuon in success page */
?>



<!-- Google Code for purchase_conversion_cleverppc Conversion Page -->
<script type=\"text/javascript\">/* <![CDATA[ */
var google_conversion_id = 947999458;
var google_conversion_language = "en";
var google_conversion_format = "2";
var google_conversion_color = "ffffff";
var google_conversion_label = "OnQiCMObumYQ4qWFxAM";
if ({{ subtotal_price }}) 
    { var google_conversion_value = {{ subtotal_price | money_without_currency }}; };
var google_conversion_currency = "EUR"; 
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js\">
    
</script>

<noscript>
<div style="display:inline;\">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/947999458/?value={{ subtotal_price | money_without_currency }}&currency_code=EUR&label=OnQiCMObumYQ4qWFxAM&guid=ON&script=0\"/>
</div>
</noscript>