<?php
/**
 * LICENSE: $license_text$
 *
 * @author    Rodrigo 
 * @copyright Copyright (c) 2016  Rodrigo
 * @license   $license$
 * @version   $Id$
 */
/**
 * waiting html
 */

?>

<div id="waitting_for_creation">
  <center>
  <br><br>
  <div class="waiting-img"><img src="<?php echo $this->getMediaUrl(); ?>wait.png"/></div>
  </center>
  <br>
  <center class="waiting_page-content">
    <?php echo $this->__('Your Adwords campaigns are now under construction.'); ?>
    
  </center>
  <center class="waiting-content">
      <?php echo $this->__('You should receive a confirmation message soon.</br>
  Campaigns will pass through a review and quality control by one of our Google Adwords account managers.</br>'); ?>
  
  <font class="waiting-message">
    <?php echo $this->__('The whole process takes usually 2 working days.'); ?>
  </font>
   <?php echo $this->__('Please be patient, we do great things.'); ?>
  </br>

  </br>
  </center>
  
  <center class="waiting-footer">
 <?php echo $this->__('For any questions, please contact us at'); ?>
     <a href="mailto:shopify@cleverppc.com"><?php echo $this->__('shopify@cleverppc.com'); ?></a></br>
  <img src="https://docs.google.com/uc?id=1h_y3PGU7HIH2J3qZ8ZzsbiJwiVjHvEvw_g" alt="Google Adwords" height="50"></center>
</div>
